### ISSUE TITLE
Issues with ++; in timer loops

### ISSUE THREAD

**Issue by xbp13x** [bmisiak/samp-precise-timers#11]
I notice when I have something like "VAR[playerid] ++;" or "VAR[playerid] = VAR[playerid] +30 "is used in a timer loop it goes a bit crazy and the value does not increase properly. I did not have this issue until trying this plugin and when removing the plugin it works fine.

As a workaround I am now using VAR[playerid] +=1; which seems to work fine.

Everything else seems to be working great, thanks for the release!

**Comment by mrreus** [comment]
I have the same problem on Debian 8.

**Comment by bmisiak** [comment]
Hi. This would indicate a very serious problem with https://github.com/ZOTTCE/samp-rs if it was indeed a reproducible issue. It doesn't look likely, but `samp-rs` is not free of bugs, as it does allow safe Rust code to break some invariants, so it's not impossible.

I for one am having trouble reproducing the bug. Are you still seeing it?

**Comment by mrreus** [comment]
Hi. The problem was in my script, so I fixed this and now it works
perfectly. And... I have a request for you - can you release a new version
(with reset native function) of samp-precise-timers? If you have a free
time of course. Thanks.

wt., 26 sty 2021 o 03:42 Brian Misiak <notifications@github.com> napisał(a):
